-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 用户资料表
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  phone TEXT UNIQUE,
  avatar_url TEXT,
  balance DECIMAL(12,2) DEFAULT 0,
  frozen_balance DECIMAL(12,2) DEFAULT 0,
  vip_level INTEGER DEFAULT 0,
  invite_code TEXT UNIQUE,
  invited_by UUID REFERENCES public.profiles(id),
  fund_password TEXT,
  bank_name TEXT,
  bank_account TEXT,
  bank_holder TEXT,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'banned', 'suspended')),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 投注记录表
CREATE TABLE IF NOT EXISTS public.bets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  game_type TEXT NOT NULL,
  period TEXT NOT NULL,
  bet_type TEXT NOT NULL,
  bet_value TEXT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  odds DECIMAL(6,2) DEFAULT 1.0,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'won', 'lost', 'cancelled')),
  win_amount DECIMAL(12,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 资金记录表
CREATE TABLE IF NOT EXISTS public.transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('deposit', 'withdraw', 'bet', 'win', 'rebate', 'bonus')),
  amount DECIMAL(12,2) NOT NULL,
  balance_before DECIMAL(12,2) NOT NULL,
  balance_after DECIMAL(12,2) NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed', 'cancelled')),
  remark TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 代理表
CREATE TABLE IF NOT EXISTS public.agents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  code TEXT UNIQUE NOT NULL,
  level INTEGER DEFAULT 1,
  total_rebate DECIMAL(12,2) DEFAULT 0,
  total_members INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 客服消息表
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id TEXT NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  sender_type TEXT NOT NULL CHECK (sender_type IN ('user', 'agent', 'system')),
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 客服会话表
CREATE TABLE IF NOT EXISTS public.chat_sessions (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  user_name TEXT,
  last_message TEXT,
  last_time TIMESTAMP DEFAULT NOW(),
  unread_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'online' CHECK (status IN ('online', 'offline', 'busy')),
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMP DEFAULT NOW()
);

-- 系统配置表
CREATE TABLE IF NOT EXISTS public.site_config (
  id INTEGER PRIMARY KEY DEFAULT 1,
  banners JSONB DEFAULT '[]',
  game_images JSONB DEFAULT '[]',
  notices TEXT[] DEFAULT '{}',
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_bets_user_id ON public.bets(user_id);
CREATE INDEX IF NOT EXISTS idx_bets_period ON public.bets(period);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON public.chat_messages(session_id);

-- 启用 RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_config ENABLE ROW LEVEL SECURITY;

-- RLS 策略 - 允许匿名访问（演示用）
CREATE POLICY "公开读取配置" ON public.site_config FOR SELECT USING (true);
CREATE POLICY "公开更新配置" ON public.site_config FOR ALL USING (true);
CREATE POLICY "公开读取用户" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "公开插入用户" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "公开更新用户" ON public.profiles FOR UPDATE USING (true);
CREATE POLICY "公开读取投注" ON public.bets FOR SELECT USING (true);
CREATE POLICY "公开插入投注" ON public.bets FOR INSERT WITH CHECK (true);
CREATE POLICY "公开更新投注" ON public.bets FOR UPDATE USING (true);
CREATE POLICY "公开读取资金" ON public.transactions FOR SELECT USING (true);
CREATE POLICY "公开插入资金" ON public.transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "公开读取代理" ON public.agents FOR SELECT USING (true);
CREATE POLICY "公开插入代理" ON public.agents FOR INSERT WITH CHECK (true);
CREATE POLICY "公开读取消息" ON public.chat_messages FOR SELECT USING (true);
CREATE POLICY "公开插入消息" ON public.chat_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "公开读取会话" ON public.chat_sessions FOR SELECT USING (true);
CREATE POLICY "公开插入会话" ON public.chat_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "公开更新会话" ON public.chat_sessions FOR UPDATE USING (true);

-- 插入默认配置
INSERT INTO public.site_config (banners, game_images, notices) VALUES (
  '[{"id":1,"image":"https://conversation.cdn.meoo.host/conversations/308104559711129600/image/2026-04-30/1777550396573-image.png","link":""}]',
  '[{"id":"xinmacau","image":"https://conversation.cdn.meoo.host/conversations/308104559711129600/image/2026-04-30/1777550396573-image.png","link":"/game/xinmacau"},{"id":"laomacau","image":"https://conversation.cdn.meoo.host/conversations/308104559711129600/image/2026-04-30/1777550396573-image.png","link":"/game/laomacau"},{"id":"canada20","image":"https://conversation.cdn.meoo.host/conversations/308104559711129600/image/2026-04-30/1777550396573-image.png","link":"/game/canada20"}]',
  ARRAY['欢迎来到大都汇', '新期即将开奖', '祝您好运']
) ON CONFLICT (id) DO NOTHING;