export const gamesContent = {
  hall: {
    titleSuffix: ' · 大厅',
    intro: (gameName: string) => `您已进入「${gameName}」游戏大厅。`,
    detail: '完整玩法与盘口接入中，可先体验已开放游戏。',
    goHk6: '前往香港六合彩',
    back: '返回上一页',
  },
  hk6: {
    title: '香港六合彩',
    subtitleLoading: '正在同步状态…',
    subtitle: (period: string, sec: number | string) =>
      `投注期 ${period} · 演示封盘倒计时 ${sec}s`,
    statsBalance: '余额',
    statsFlow: '流水',
    statsPnl: '输赢',
    statsRebate: '回水',
    statsDash: '—',
    prevDraw: '上期',
    noDraw: '暂无开奖数据',
    historyBtn: '历史开奖',
    betSummary: '下注总额',
    totalTicketsPrefix: '共',
    totalTicketsSuffix: '注单',
    stakeInputAria: '单注金额',
    bet: '下注',
    betting: '提交中…',
    reset: '重置',
    historyTitle: '历史开奖',
    historyLoading: '加载中…',
    historyEmpty: '暂无记录',
    close: '关闭',
    alertLogin: '请先登录后再下注',
    alertNoSelection: '请先选择注项',
    alertBadStake: '请输入有效下注金额',
    betSuccess: (total: string) => `下注成功，合计 ¥${total}`,
    betFail: '下注失败',
    networkError: '网络错误',
    ariaBack: '返回',
    row2Aria: '上期开奖',
    betPlateAria: '下注盘',
    summaryAria: '投注汇总',
  },
} as const;
