export const gamesContent = {
  hall: {
    titleSuffix: ' · 大厅',
    intro: (gameName: string) => `您已进入「${gameName}」游戏大厅。`,
    detail: '完整玩法与盘口接入中，可先体验已开放游戏。',
    goHk6: '前往香港六合彩',
    back: '返回上一页',
  },
  hk6: {
    title: '香港六合彩',
    subtitleLoading: '正在同步状态…',
    syncFailed: (code: string) =>
      code === 'fetch_failed'
        ? '同步失败：服务器连不上开奖源（请检查出站网络或代理）'
        : `同步失败（${code}）`,
    subtitle: (period: string, sec: number | string) =>
      `投注期 ${period} · 演示封盘倒计时 ${sec}s`,
    syncSource: '同步',
    statsBalance: '余额',
    statsFlow: '流水',
    statsPnl: '输赢',
    statsRebate: '回水',
    statsDash: '—',
    prevDraw: '上期',
    noDraw: '暂无开奖数据',
    historyBtn: '历史开奖',
    betSummary: '下注总额',
    totalTicketsPrefix: '共',
    totalTicketsSuffix: '注单',
    stakeInputAria: '单注金额',
    bet: '下注',
    betting: '提交中…',
    reset: '重置',
    historyTitle: '历史开奖',
    historyLoading: '加载中…',
    historyEmpty: '暂无记录',
    close: '关闭',
    alertLogin: '请先登录后再下注',
    alertNoSelection: '请先选择注项',
    alertBadStake: '请输入有效下注金额',
    betSuccess: (total: string) => `下注成功，合计 ¥${total}`,
    betFail: '下注失败',
    networkError: '网络错误',
    ariaBack: '返回',
    row2Aria: '上期开奖',
    betPlateAria: '下注盘',
    summaryAria: '投注汇总',
    comboMode: '复式玩法',
    comboAdd: '加入注单',
    comboClear: '清空当前所选',
    comboPickPrefix: '请按玩法选满',
    comboPickUnit: '项',
    quickTabManual: '标准复式',
    quickTabQuick: '胆拖 / 对碰',
    quickAdded: (n: number) => `已加入 ${n} 条注项`,
    quickCap: `单次最多生成 ${480} 条，已截断`,
    quickEmpty: '条件不足或注项已全部在清单中',
    quickDragNums: '连码胆拖（号码）',
    quickDragZT: '生肖连 / 尾数连胆拖',
    quickPeng: '对碰（批量二码 / 三全中）',
    quickNumPat: '先点「胆」或「托」，再在下方选号；胆满后切换为托。',
    quickSz2Two: '三中二 · 2 胆 + 若干托（例：08、18 托 19–21）',
    quickSz2One: '三中二 · 1 胆 + 托中任取 2 个成组',
    quickSz3: '三全中 · 2 胆 + 每托成一组',
    quickEq2: '二全中 · 1 胆 + 每托一组',
    quickE2t: '二中特 · 1 胆 + 每托一组',
    quickTc: '特串 · 1 胆 + 每托一组',
    quickBucket: '点选格子前，先选择正在编辑胆码还是托码：',
    quickBank: '胆',
    quickTuo: '托',
    quickClear: '清空',
    quickGen: '一键加入注单',
    quickSzlHit: '中',
    quickSzlMiss: '不中',
    quickSzlPat: '二肖连：1 胆肖 + 若干托肖；三/四肖连：1 胆肖 + 托中任选 2/3 个生肖组单。尾连同理（1 胆尾 + 若干托尾）。',
    quickSzl2: '二肖连',
    quickSzl3: '三肖连',
    quickSzl4: '四肖连',
    quickWl2: '二尾连',
    quickWl3: '三尾连',
    quickWl4: '四尾连',
    quickBankZ: '胆肖',
    quickTuoZ: '托肖（可多选）',
    quickBankTail: '胆尾（0–9）',
    quickTuoTail: '托尾（可多选）',
    quickPengKind: '预览',
    quickPengZ: '生肖对碰（两肖号码 cross）',
    quickPengT: '尾数对碰',
    quickPengZT: '生肖尾数对碰（该肖中指定尾号的号码两两组合）',
    quickPengSz3: '三肖三全中（三肖各一号全交叉）',
    quickZLeft: '生肖 A',
    quickZRight: '生肖 B',
    quickZThird: '生肖 C',
    quickLmSub: '连码类型',
    quickTailA: '尾数 A',
    quickTailB: '尾数 B',
    quickGenPeng: '生成对碰注单',
  },
} as const;
