/** 充值 / 提现 / 资金记录 */
export const walletContent = {
  deposit: {
    pageTitle: '充值',
    payLabel: '支付方式',
    amountLabel: '存款金额（元）',
    amountPlaceholder: '请输入存款金额',
    quickLabel: '快捷金额',
    submit: '确定存款',
    submitting: '处理中…',
    hintAfterApi:
      '订单将提交至系统并记入资金流水，同时可打开在线客服发送充值留言。',
    recordsLink: '查看存款记录 →',
    gateTitle: '请先登录',
    gateDesc: '登录后方可提交充值并写入资金流水。',
    backHome: '返回首页',
    errorFallback: '充值提交失败',
    payTabLabels: {
      alipay: '支付宝',
      wechat: '微信',
      usdt: 'USDT（赠送1%）',
    },
    payMessageLabels: {
      alipay: '支付宝',
      wechat: '微信',
      usdt: 'USDT',
    },
  },
  withdraw: {
    pageTitle: '提现',
    gateTitle: '请先登录',
    gateDesc: '登录后方可提交取款申请。',
    backHome: '返回首页',
    amountError: '请输入有效金额',
    minAmountError: '单笔提现金额须不少于 100 元',
    pwdError: '请输入交易密码',
    methodError: '请先选择收款方式',
    tradePwdLabel: '交易密码',
    hintMin: '单笔提现金额须不少于 100 元（与系统规则一致）。',
    requestFail: '取款申请失败',
  },
  records: {
    pageTitle: '资金记录',
    gateTitle: '请先登录',
    gateDesc: '登录后可查看账户资金流水。',
    backHome: '返回首页',
    loading: '加载中…',
    fromServer: '数据来自服务端资金流水。',
    refresh: '刷新',
    empty: '暂无记录',
    loadFail: '加载失败',
    table: {
      time: '时间',
      type: '类型',
      amount: '金额',
      status: '状态',
    },
  },
} as const;
